### ISSUE TITLE
panic: runtime error: invalid memory access or nil pointer deference

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#11]
Haven't quite found a reproc, but something about the current folder of files im working on causes the program to crash out with this error, perhaps an issue with a unopenable file? Not sure how much sanity checking you are doing

**Comment by Masamune3210** [comment]
Ok, yeah im almost certain that is at least the source of the issue, some of the files in the folder are incorrectly built

**Comment by giwty** [comment]
Did you get any additional printout besides this error?

**Comment by Masamune3210** [comment]
I'll see if I can retrigger it in a bit, but I didn't see much other than the traceback into the library that faulted, which come to think of it might be useful

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/86275380-cc959680-bb98-11ea-9f57-efdd717c69a5.png)

**Comment by giwty** [comment]
Thanks, definitely helps.
Do you know what is the file that causes this error?
Knowing the title id can help, but not required to fix this.

**Comment by Masamune3210** [comment]
it was a folder of files for 01009CC00C97, 01005D6003B7, and 010054A0085C, cant narrow it down farther as I already recreated the damaged files I believe

**Comment by giwty** [comment]
Thanks, please check latest version, i've added many more validation checks, it should not crash again, and hopefully we will get a nice log message.

**Comment by Masamune3210** [comment]
Already tried, seems to be working. Won't know for sure until I get around to doing the next batch. Will let you know. Nice touch on the dup check, could that be in a list like the dlc and updates perhaps?

**Comment by Masamune3210** [comment]
Had it happen again, but I managed to figure out the trigger! It seems that for some reason the app will not notice that the titles and versions json's are missing and won't attempt to download them. Which ends horribly as it tries to use the file that doesnt exist

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/86502712-bee43a80-bd6b-11ea-9ecd-e5ea4ce9fce2.png)

**Comment by giwty** [comment]
Thanks, just pushed a fix for this.
