### ISSUE TITLE
GUI does not work in latest release

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#12]
with previous settings file, brings up console, downloads lists, and then exits
without previous settings file, provisions files and then sits on a white screen

'2020/07/03 18:38:42 astikit: starting worker...
2020/07/03 18:38:42 Starting...
2020/07/03 18:38:42 Provisioning...
2020/07/03 18:38:42 Astilectron has already been provisioned to version 0.39.0, moving on...
2020/07/03 18:38:42 Electron has already been provisioned to version 7.1.10, moving on...
2020/07/03 18:38:42 Listening...
2020/07/03 18:38:42 Executing...
2020/07/03 18:38:42 Starting cmd C:\Users\AppData\Roaming\Switch Library Manager\vendor\electron-windows-amd64\electron.exe C:\Users\AppData\Roaming\Switch Library Manager\vendor\astilectron\main.js 127.0.0.1:11422 false
2020/07/03 18:38:42 Stdout says:
2020/07/03 18:38:42 Astilectron says: {"name":"app.event.ready","targetID":"app","displays":{"all":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1040},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1040},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":1920,"y":27,"width":1680,"height":1050},"workArea":{"x":1920,"y":27,"width":1680,"height":1010},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1680,"height":1050},"workAreaSize":{"width":1680,"height":1010},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}],"primary":{"id":2528732444,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1040},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1040},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}},"supported":{"notification":true}}
2020/07/03 18:38:42 Sending to Astilectron: {"name":"window.cmd.create","targetID":"1","sessionId":"2","url":"w:\\Console Files\\Switch\\nsp-update\\web\\app.html","windowOptions":{"center":true,"height":700,"title":"Switch Library Manager","width":700}}
2020/07/03 18:38:42 Astilectron says: {"name":"window.event.focus","targetID":"1"}
2020/07/03 18:38:43 Astilectron says: {"name":"window.event.did.finish.load","targetID":"1"}
2020/07/03 18:38:43 astikit: worker is now waiting...
2020/07/03 18:38:43 Astilectron says: {"name":"window.event.blur","targetID":"1"}'

**Comment by giwty** [comment]
Do you have this file "app.html" located in w:\Console Files\Switch\nsp-update\web\app.html?
The web folder should be in the same folder as the "exe"

**Comment by giwty** [comment]
Also, with previous settings file (non GUI mode), you should continue running it through the command line, and not by double clicking

**Comment by Masamune3210** [comment]
Nope, didn't see the folder or any extra files other than the version lists and the settings

**Comment by giwty** [comment]
If you build on your own, you will need to copy over the web folder from the source, or from the release zip

**Comment by Masamune3210** [comment]
Didnt notice the extra folder in the release archive, my bad lol
