### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by ceedveed** [giwty/switch-library-manager#13]
Windows 10 x64 v1909

I set folder for library. After I receive this message:

![image](https://user-images.githubusercontent.com/22138700/86524531-51a2d900-be41-11ea-980f-02d2adc02b92.png)

**Comment by giwty** [comment]
Does it happen every-time you select the folder?
Can you please provide the logs from the command window?

**Comment by ceedveed** [comment]
> Does it happen every-time you select the folder?
> Can you please provide the logs from the command window?

After the initial setup, it shows this error. I can see the GUI try to scan the folder that was initially set. I cannot get to the command window because it disappears when this error windows pops up.

**Comment by giwty** [comment]
I've changed the output to a log file, and added some error messages to the UI.
Please use this build and attach the log if it fails again.
[switch-backup-manager (Windows).zip](https://github.com/giwty/switch-library-manager/files/4874459/switch-backup-manager.Windows.zip)

**Comment by ceedveed** [comment]
After running the attachment, this is the log:

`ERROR[0005]open titles.json: The system cannot find the file specified.  app_name=switch-backup-manager`

**Comment by giwty** [comment]
Thanks, glad it is working.
I've just pushed the titles/versions json files and changed so you can work with the app offline.
Will be part of next release
