### ISSUE TITLE
JavaScript Uncaught Exception on v1.1

### ISSUE THREAD

**Issue by Hielock** [giwty/switch-library-manager#14]
I just tried to run the 'exe', it loads but later says "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:183:27).

Also when I tried to use with "gui = false" it says:
Checking for missing updates
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x73098b]

goroutine 1 [running]:
github.com/giwty/switch-backup-manager/process.ScanForMissingUpdates(0xc005cc8870, 0xc0056d17a0, 0x0)
        /Users/twig/IdeaProjects/nsp-update/process/incompleteTitleProcessor.go:29 +0x13b
github.com/giwty/switch-backup-manager/ui.processMissingUpdates(0xc005cf2c70, 0xc000352070)
        /Users/twig/IdeaProjects/nsp-update/ui/cmd.go:129 +0x5d
github.com/giwty/switch-backup-manager/ui.ConsoleGUI()
        /Users/twig/IdeaProjects/nsp-update/ui/cmd.go:114 +0x910
main.main()
        /Users/twig/IdeaProjects/nsp-update/main.go:15 +0x60

Hope you can fix it, it's an incredible and useful program (used to use non-gui version 0.4 and recently discovered this but doesn't run properly).
Thanks for all!

**Comment by giwty** [comment]
Can you please attach the log file (switch-back-manager.log) ?

**Comment by JrRadiant** [comment]
Same problem with me. Hmm, but where to find that log?..

**Comment by aur0n** [comment]
Same error here. No log file in the folder is generated.

**Comment by giwty** [comment]
New version is out, please try and let me know if still happens

**Comment by Hielock** [comment]
Sorry about my late response but I neither found the '.log' file, I even look into AppData or Temp files but nothing..

I'll try the newer version right now and let you know if the problem it's solved. 

And for now thanks for all your effort!

**Comment by Hielock** [comment]
With the first running I got same error (Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:183:27), and with the second attemp it says the following (both on GUI version): 
![image](https://user-images.githubusercontent.com/68199784/87478861-0da59600-c5f0-11ea-97f4-65f045de24c7.png)

And now I can see a log file in the folder, but it's empty, I don't know why :S
Regards and thanks again!

**Comment by Masamune3210** [comment]
exception is happening to me too, let me know if you need any testing or info

**Comment by Masamune3210** [comment]
Could you possibly add a debug mode of sorts where the program lists the files as it processes them? would probably make tracking down these errors easier as the issued file could be found easier

**Comment by giwty** [comment]
New release with bug fixes is out, please see if this still happens.
Also added a centralized log, with a debug mode to allow for easy troubleshooting.
Please update this issue if still happens and attach the slm.log.

**Comment by Hielock** [comment]
Now it works!! Just smoothly :]
Thank you so much!! 

Note: It doesn't detect XCI files (maybe because I don't put the .keys file), could be useful that the title parsing function also works with XCI/XCZ.
