### ISSUE TITLE
XCI/XCZ support

### ISSUE THREAD

**Issue by mspykerez** [giwty/switch-library-manager#15]
Hi there mate,
Nice program you have here!

My only wish is that you add XCI/XCZ support for it to be perfect.

**Comment by Hielock** [comment]
Hey! :]
You can just change the extension for that (cmd: ren *.xci *.nsp).
But also could be cool if it's officially implemented.

**Comment by mspykerez** [comment]
You mean renaming the file extension to .nsp ? that does not work, gives a error when trying to read the file.

**Comment by Hielock** [comment]
@mspykerez Exactly! But no, just change the file extension to '*.nsp' and look for updates with this software (it only uses the file name, not the content, to compare it with a database); later, when you already have the list of pending updates just go back and rename files with '*.xci' extension again to use them on Switch :]

**Comment by mspykerez** [comment]
Unfortunately I do not have proper file names in order of this to work as you say. The file names of my .xci files are pretty random, only the folders have the game name.

**Comment by Hielock** [comment]
mmmm :S
As I understand you need that specific info in the name of the files to make this program work.
You can try some of the following:
Rename the folder to .nsp, it could work XD (but I'm not sure)
Or copy the folder names to the xci games  
Also you can use NSC-Builder, that program automatically rename the output files using the format: Title + Title ID + Version + [#Games #Updates #DLC], it's useful..
Then you can use this program to look for missing updates/DLC

Regards!

**Comment by mspykerez** [comment]
As I read somewhere this tool is capable of scanning any NSP and get the info it requires (Read titleId/version by decrypting NSPs (requires prod.keys)) So my only wish is if it did the same for XCI files.

**Comment by Hielock** [comment]
Oh! I see, yeap! That's true  :] 
Now the decrypting method was implemented, as you wrote..
Well.. I think we just have to wait, in my case I can't run the program on Windows :S
Hope the developer can fix it and add functions (like XCI decrypting/parsing support).  I'm concient of the difficulty of that and that it recquires time, but it's a great and useful program, it worth it! :D ... If I knew more of programming maybe could help with something, but I'm just a beginner/noob in that... :/
Also later I'll try with Linux... maybe It works there.

Anyway.. regards and see ya around!

**Comment by giwty** [comment]
XCI/NSZ support added :)
