### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer exception

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#16]
With the latest release as of a couple hours ago

![image](https://user-images.githubusercontent.com/1053504/88741433-3dcb5980-d105-11ea-8fba-3059359e5a4f.png)

**Comment by Masamune3210** [comment]
Ignore the folder name, im lazy and haven't renamed it lol

**Comment by giwty** [comment]
Fixed, was an issue with the logging framework i'm using.
Please re-download
