### ISSUE TITLE
Add new game revisions

### ISSUE THREAD

**Issue by mspykerez** [giwty/switch-library-manager#17]
Is it possible to add a new TAB that lists new base game revisions available on the market ? Example:

Super_Mario_Odyssey_v001_NSW-JRP > this is rev001 of the cartridge.  rev000 is Super.Mario.Odyssey.NSW-BigBlueBox
The.Legend.of.Zelda.Breath.of.the.Wild.v002.NSW-BigBlueBox > this is rev002 (1.5.0)

edit: would also like to know the selected few games that have physical (cartridge) releases vs eShop releases which can have different revisions as well.

**Comment by giwty** [comment]
I dont think i have access to this information...
If there is anywhere i can query for revisions then this could be possible, but i'm not sure where.

**Comment by giwty** [comment]
Closing as out of scope
