### ISSUE TITLE
Add game regions

### ISSUE THREAD

**Issue by mspykerez** [giwty/switch-library-manager#18]
Can game regions be added? I want to know if a game is available on other regions (USA, EUR, etc) or if it's the same for USA, EUR, etc ? Sometimes they have different versions of the same game.

**Comment by giwty** [comment]
I can add region to the table showing the files in your local library, but it sounds like you are looking for a new table that shows any missing games not in your local library?

**Comment by mspykerez** [comment]
To explain better I was looking for a way to know if a game on my library also has a different version released on a different region. Useful to know because sometimes they release the same game on different regions slightly modified with new stuff or has censored parts, etc,

**Comment by giwty** [comment]
Will be part of next release

**Comment by giwty** [comment]
Added in 1.3.7
