### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#19]
Another error with the new build
![image](https://user-images.githubusercontent.com/1053504/88849689-dc13f980-d1af-11ea-9db0-93b8dc59ca89.png)

**Comment by giwty** [comment]
Thanks, i'll fix that.
btw, you can turn on debug mode and see exactly which file is causing the problem. (it's an update file with no base game).

**Comment by Masamune3210** [comment]
I can't get debug to do anything, even with debug=true. Is there a specific command to use it? Do the command prompt arguments even work still other than -f ?

**Comment by giwty** [comment]
Strange, marking debug=true in the settings.json should have debug output to the slm.log in either GUI or console modes.
Are you not seeing the slm.log at all?

**Comment by Masamune3210** [comment]
I am now, must have been either a messed up setting or just windows being dumb

**Comment by giwty** [comment]
Cool, closing this, will be part of next release
