### ISSUE TITLE
Renaming files for compatibility with the Switch filesystem

### ISSUE THREAD

**Issue by pixeltester** [giwty/switch-library-manager#20]
As part of the renaming process would it be possible to add support for renaming folders and files to be compatible with the Switch filesystem? It seems that it can't deal with unicode and Japanese characters and so on that are in many title names, if they are used locally on the Switch, on the SD card for example, then homebrew cannot deal with or see them. There are other storage methods that have issues with these characters too. Maybe a filter to change to characters and perhaps convert Japanese to Romaji.

Here is something of an explanation of the issue: https://github.com/switchbrew/libnx/issues/90#issuecomment-390697783

**Comment by giwty** [comment]
Makes sense, will include this in the next update

**Comment by Masamune3210** [comment]
if it makes it easier, nsc_builder can translate between original and romanji, might look at that for help if needed

**Comment by giwty** [comment]
should be fixed in 1.1.6

**Comment by pixeltester** [comment]
> 
> 
> should be fixed in 1.1.6

Great, will report if any issues after testing. However I don't see a mention of unicode character handling which is half of the issue.
