### ISSUE TITLE
All games updated

### ISSUE THREAD

**Issue by trekastana** [giwty/switch-library-manager#21]
when I scan the games it indicates that they are all updated, I have it in nsz format and I know there are new updates for some games.

**Comment by giwty** [comment]
Please re-run in debug mode (set it in the settings.json), and attach the slm.log here.
Can't really help without additional details.

**Comment by trekastana** [comment]
Thanks Giwty. I ran it in debug mode. I attach the log file.
[slm.log](https://github.com/giwty/switch-library-manager/files/5023039/slm.log)

**Comment by giwty** [comment]
Looks like Tinfoil had some issues with updating the versions info, which i'm using as the source of truth.
Last update was 12d ago, so you are seeing the state as of 12 days ago.
This should be fixed tonight/tomorrow according to blawar [(https://github.com/blawar/titledb/issues/6)]
Once it's updated, the app will download the new versions info, and reflect any missing updates.
