### ISSUE TITLE
Latest release not working on Mac

### ISSUE THREAD

**Issue by Elionna** [giwty/switch-library-manager#22]
terminal gets stuck on this part and never launches the app, the previous releases are working perfectly

% /Applications/switch-library-manager.mac/switch-library-manager ; exit;
 INFO[0000]astikit: starting worker...
Downloading/Validating electron files .. (can take 1-2min)
 INFO[0000]astikit: worker is now waiting...

**Comment by giwty** [comment]
Please try to delete the vendor folder (inside the web folder).
This might be because of the app rename.

**Comment by Elionna** [comment]
I deleted it but the issue persists, even on the latest release

**Comment by Elionna** [comment]
nevermind, it looks like this creates files in the user folder, once I cleared those out the app began to work
