### ISSUE TITLE
Renaming files for compatibility with the Switch filesystem (Part 2)

### ISSUE THREAD

**Issue by pixeltester** [giwty/switch-library-manager#23]
The last issue was closed by @giwty Since I can't reopen it and you may have missed my reply I'm opening this one.

Although Japanese was taken care of part of the issue was unicode characters which have the same problem. 

Additionally for people who do not want or need to transliterate or remove/convert unicode characters because they do not use any files locally on the Switch, I believe you should have these rename features as a switch in the json.

**Comment by Masamune3210** [comment]
@giwty is the repo owner, so I'm sure they know they closed it lol.

**Comment by pixeltester** [comment]
> @giwty is the repo owner, so I'm sure they know they closed it lol.

I know who the owner is and I didn't say giwty didn't know they closed it, I'm implying that they missed part of the issue. 
Furthermore github issues are for bug reports, constructive suggestions and so on. Please keep these kinds of one liner immature comments on your facebook/twitter blogs/vlogs.

**Comment by giwty** [comment]
Missed the unicode part, will handle it in the next release.

**Comment by Masamune3210** [comment]
@pixeltester you seem fun....

**Comment by giwty** [comment]
Fixed in 1.2.5
