### ISSUE TITLE
different folders

### ISSUE THREAD

**Issue by mspykerez** [giwty/switch-library-manager#24]
Would be great if we could add different folders, even if they are on different hard disks, at the same time for the app to scan.
One might have games on drive A and updates on drive B so having the ability to add both folders or even more would do the trick.

**Comment by giwty** [comment]
Just need to figure out an intuitive UI for this, and then i'll get it in.

**Comment by giwty** [comment]
https://github.com/giwty/switch-library-manager/commit/1b901eb5380301f30bda42f128225851fff71423
