### ISSUE TITLE
Downloading/validating electron files...

### ISSUE THREAD

**Issue by seriouslyunderappreciated** [giwty/switch-library-manager#26]
Every time I launch this app it gets stuck doing this, I have to close and reopen it for it to work. Waiting does nothing :(

Next launch tells me folder is not set and prod keys is missing. Finally the third launch it works just fine.

**Comment by giwty** [comment]
This is likely because of a corrupted download.
Please try to delete the "vendor" folder inside the "web" folder, and try again.
Planning to address this in future version

**Comment by seriouslyunderappreciated** [comment]
There's no vendor folder anywhere :(

**Comment by giwty** [comment]
Next release will already be packaged with the vendor folder as part of the binary, this should fix many issues, including yours.
Stay tuned

**Comment by giwty** [comment]
Fixed in 1.2.5
