### ISSUE TITLE
CreateLocalSwitchFilesDB crash

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#27]
![image](https://user-images.githubusercontent.com/1053504/90708075-969e9580-e25e-11ea-87f7-c411a1ba3e7d.png)

**Comment by Masamune3210** [comment]
Sorry it took so long to try this one, been busy with work

**Comment by giwty** [comment]
Thanks, I've stopped using console mode, so didn't see that issue.

**Comment by Masamune3210** [comment]
Is there any way to omit creating the database? I really dont need it currently if thats whats causing the issue

**Comment by giwty** [comment]
https://github.com/giwty/switch-library-manager/commit/304e8d4946f1d6a1cb8d0ff89917d09e82d90309
are you using mac? i can create a build for you until i release a new version

**Comment by Masamune3210** [comment]
nope, windows and linux

**Comment by Masamune3210** [comment]
if its a problem i can take a crack at compiling it, as it doesnt seem too hard to do

**Comment by giwty** [comment]
[switch-library-manager.linux.zip](https://github.com/giwty/switch-library-manager/files/5100479/switch-library-manager.linux.zip)
[switch-library-manager.windows.zip](https://github.com/giwty/switch-library-manager/files/5100483/switch-library-manager.windows.zip)

**Comment by Masamune3210** [comment]
Seems to work fine! Thanks! Before I go, would you rather one long issue instead of new issues each time? Or should I just keep making a new issue for each problem? Little late, but figured I would ask

**Comment by giwty** [comment]
The database really speed things up (more then 10x), and regardless it wasn't the root cause of the issue.
A separate issue per problem is ideal, and thanks for helping improve this program!

**Comment by Masamune3210** [comment]
Not a problem at all! I like helping with stuff like this, and I use the program all the time so it only makes sense that I would try to help fix issues if I find them
