### ISSUE TITLE
Program looks weird in Windows 10 Terminal Beta

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#3]
Program looks amazing in PowerShell and Command Prompt, but if you use the Terminal Beta that Microsoft have been testing to eventually replace the other two, the program ends up looking really weird. Either something to do with the way you handle coloring the background or the padding goes haywire and the program just ends up a jumbled mess. Can supply screenshots if needed

**Comment by giwty** [comment]
Thanks for this, i'll wait until terminal goes out of beta and see how things behave.

**Comment by giwty** [comment]
Added GUI, closing this
