### ISSUE TITLE
Some files failing to be sorted into folders correctly

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#31]
Having a issue where some files will be seemingly ignored by the program, only leaving this in the logs. Seems the program is trying to access the file incorrectly, for some reason it's prepending the non-romanji name of a file as a folder before using the correct name.

![image](https://user-images.githubusercontent.com/1053504/91626213-db1ee500-e972-11ea-845b-5af99c53acc9.png)

**Comment by Masamune3210** [comment]
Nevermind, I see what its doing, I misread the log. The issue is its trying to create a folder with illegal chars, specifically in this case the <> brackets, maybe replace illegal chars with a space?

**Comment by Masamune3210** [comment]
Any updates on this? Don't mean to rush, just wanted to make sure the issue report wasn't missed or something

**Comment by giwty** [comment]
Not missed, just busy with life.. should be able to get this done in the next couple of days.

**Comment by Masamune3210** [comment]
It's fine, I understand completely lol. Have it stopgapped on my end by using the linux build inside of WSL

**Comment by giwty** [comment]
Issue was found and fixed, will be part of next release this weekend

**Comment by giwty** [comment]
Fixed in 1.2.5
