### ISSUE TITLE
Version info renaming

### ISSUE THREAD

**Issue by Buzbee** [giwty/switch-library-manager#34]
Can you add another box for version number so that files can be renamed like
"{TITLE_NAME} [{DLC_NAME}][{TITLE_ID}][v{VERSION}][{VER_NUMBER}]"
A Hat in Time [010056E00853A800][v262144][1.0.4]

Also, is it possible to pull {VERSION} for DLC?
A Hat in Time [Nyakuza Metro][010056E00853B002][v65536]

**Comment by giwty** [comment]
Added {VERSION_TXT} for updates/base
DLC already supports the update id ({VERSION})
