### ISSUE TITLE
Can't retrieve package for building

### ISSUE THREAD

**Issue by pixeltester** [giwty/switch-library-manager#36]
go get -u github.com/giwty/switch-library-manager

cannot find package "github.com/schollz/progressbar/v2" in any of:
       c:\go\src\github.com\schollz\progressbar\v2 (from $GOROOT)

**Comment by giwty** [comment]
Thanks, i've updated the build instructions the use the new bundle tool.
Please avoid using 'go get', and just clone the repo using git.
Let me know if you still have issues.

**Comment by pixeltester** [comment]
> 
> 
> Thanks, i've updated the build instructions the use the new bundle tool.
> Please avoid using 'go get', and just clone the repo using git.
> Let me know if you still have issues.

No issues with that now, thank you.
