### ISSUE TITLE
Console version removed?

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#37]
Are the console commands no longer a thing? I use the program from PowerShell, and now instead of getting any output to the console I just get immediately returned with the output happening in the background, with no output on the console

**Comment by Masamune3210** [comment]
No command output on command prompt either, so its not an issue with the terminal used

**Comment by giwty** [comment]
Not intentionally... while i figure this out, please follow these steps to build a console version:
- Install and setup Go
- Clone the repo: git clone https://github.com/giwty/switch-library-manager.git
- Get the bundler: go get -u github.com/asticode/go-astilectron-bundler/...
- Install bundler: GOBIN=/usr/local/bin/ go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
- Copy bundler binary to the source folder cd switch-library-manager and then mv /usr/local/bin/astilectron-bundler .
- Execute ./astilectron-bundler db
- env GOOS=windows GOARCH=amd64 go build

If needed, i can attach do the build for you.
Will update the release with console compatible versions latter today/tomorrow

**Comment by Masamune3210** [comment]
I'm in between batches right now so I'll just wait for the release, no rush. Was just testing the build and noticed the issue

**Comment by giwty** [comment]
Here is the windows version, let me know if you need linux as well
[switch-library-manager.exe.zip](https://github.com/giwty/switch-library-manager/files/5216065/switch-library-manager.exe.zip)

**Comment by Masamune3210** [comment]
Thanks, will test it tomorrow and let you know if it's fixed!

**Comment by Masamune3210** [comment]
Console output works again, Thanks!
