### ISSUE TITLE
macOS < 10.14 support

### ISSUE THREAD

**Issue by ivanmarban** [giwty/switch-library-manager#38]
I'm running macOs 10.13.6 as my iMac mid 2011 only supports macOS High Sierra. Is it possible to make this app compatible with previous versions ? I'm getting a message that I can't run it because of my macOS version.

**Comment by giwty** [comment]
It should work i think... 
What error are you getting?

**Comment by ivanmarban** [comment]
![01](https://user-images.githubusercontent.com/5158905/94128707-c1ca6500-fe5a-11ea-9648-d9e7f2e33e4f.png)
![02](https://user-images.githubusercontent.com/5158905/94128719-c68f1900-fe5a-11ea-9d02-0d7d2b3d8254.png)

Translated to English:

"This version of application Switch-Library-Manager.app can not be used with this version of macOS. You have installed v10.13.6 of macOS. This application needs macOS 10.14 or later"

**Comment by KingHavok** [comment]
Same issue here. 

![Screen Shot 2020-10-03 at 2 28 44 pm](https://user-images.githubusercontent.com/44717004/94983301-d0b0c600-0584-11eb-9c84-d89a75099c13.png)
![Screen Shot 2020-10-03 at 2 28 44 pm](https://user-images.githubusercontent.com/44717004/94983303-d27a8980-0584-11eb-888b-8d396df9ef42.png)

**Comment by KingHavok** [comment]
I've compiled it under xcode 10.1 (to support macos 10.13). 

One glitch
- the code makes assumptions about the version of astilectron
- it appears to hardcode the directory within which it was compiled as a source for something

	/Users/kinghavok/Downloads/switch-library-manager-1.3.5/gui.go:273
github.com/asticode/go-astilectron.(*Window).OnMessage.func1.1

**Comment by giwty** [comment]
Can you please this version and report if it is working for you?
https://drive.google.com/file/d/1zwTVW0V9YQM4oN16st055CyCu9gBGLzA/view?usp=sharing

**Comment by ivanmarban** [comment]
Working on macOS High Sierra version 10.13.6 (17G14033)

**Comment by giwty** [comment]
Thanks for confirming, future release will work with 10.13

**Comment by giwty** [comment]
Fixed in 1.3.7
