### ISSUE TITLE
prod.key not being found

### ISSUE THREAD

**Issue by tremofox** [giwty/switch-library-manager#41]
I tried adding the prod.keys to the folder the .exe was in, the folder the games were in, a .switch folder in the .exe and games folders but still they wouldn't be found by the app.

**Comment by giwty** [comment]
Added option to specify the path in the settings.json.
Let me know if that helps you.
https://github.com/giwty/switch-library-manager/commit/fb69a0181252d5a089e7b359713fe8142c1def09
