### ISSUE TITLE
Renaming Bug?

### ISSUE THREAD

**Issue by Buzbee** [giwty/switch-library-manager#45]
1. DLC pack 1 has space between Zelda and Breath but the space is missing in DLC pack 2.

The Legend of Zelda Breath of the Wild [The Legend of Zelda Breath of the Wild DLC Pack 1][01007EF00011F001][v196608][1.6.0].nsp

The Legend of Zelda Breath of the Wild [The Legend of ZeldaBreath of the Wild DLC Pack 2][01007EF00011F001][v196608][1.6.0].nsp

I guess this is Nintendo's fault.The titles.json has
"name": "The Legend of Zelda: \nBreath of the Wild DLC Pack 1",
"name": "The Legend of Zelda:\nBreath of the Wild DLC Pack 2",

2. Not sure if this is a windows issue or bug.
 CAPS/No caps may or may not rename in all caps/no caps based off the original filename (if all characters match besides capitalization):

so I end up with this after organization:

Super Mario Odyssey [0100000000010000][v0][1.0.0].nsp
SUPER MARIO ODYSSEY [0100000000010800][v262144][1.3.0].nsp

Changing the filename title name then running organization again fixed the problem.

You could work around this issue by first renaming all existing files by {TITLE_ID}{VERSION} then by file_name_template in settings.json. If folders already exist for games not created by your program you could also run into this problem with folders.

**Comment by giwty** [comment]
Thanks for the report, i'll add logic to handle these cases

**Comment by giwty** [comment]
First issue will be fixed in the next release.
2nd issue is happening because Windows has a case insensitive file system, so when trying to rename from upper to lower or vice versa, it will essentially be a no op.
I can potentially identify that, and do a double rename (as you suggested), but for now i'm not going to handle that.

**Comment by giwty** [comment]
Partially fixed in 1.3.7
