### ISSUE TITLE
Split Files

### ISSUE THREAD

**Issue by johnlescault** [giwty/switch-library-manager#48]
When using the organize button
- The split file should not be renamed (it needs to keep 00, 01). Those files need to be in a separate folder (The folder can be renamed no problem. This is to make it recognizable by the switch. 
- It would be nice if the folder attribute could be changed to be ready to archive (this allows the switch to see the folder as a single file in order to install).
- Only the 00 file is currently getting copied over (and renamed). The other files stay in the 'old' folder.

**Comment by giwty** [comment]
Yeah, i screwed up the organize behavior with split files, will sort it out in the next release.

**Comment by giwty** [comment]
Fixed in 1.3.7
