### ISSUE TITLE
Old update files are not deleted

### ISSUE THREAD

**Issue by spencerdiniz** [giwty/switch-library-manager#49]
Hi,

First I'd like to thank you for providing this great app.

I would like to report a bug. The feature to delete old update files is not working for me.
I have `"delete_old_update_files": true` in the configuration file, old update files are detected and listed in the Issues tab, but they aren't deleted. I've been manually deleting them, based on the list in Issues tab. 

I'm running the macOS GUI version on macOS Catalina (10.15.7).

_I suspected this may be a permissions problem. In fact, in order for Switch Library Manager to run at all, I had to put it in the Applications folder. I doesn't launch at all from the Downloads folder._

Thanks again.

**Comment by giwty** [comment]
That's actually me screwing up the in the latest version, setting the old update deletion to always false.
Will be fixed in the release.

**Comment by giwty** [comment]
Fixed in 1.3.7

**Comment by spencerdiniz** [comment]
Thanks!
