### ISSUE TITLE
Possible to support multicontent nsp?

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#5]
Would it be possible to add support for multicontent nsp files? I assume it would take extracting the titleids from the file itself since the file would have more than one title id at that point

**Comment by giwty** [comment]
Not sure what is multi content NSP, but i have now added the ability to look into NSP files (decrypt headers, PFS0..)
So this can be added now

**Comment by Masamune3210** [comment]
I'll work on finding some documentation but as far as I understand it unless im wrong, its just multiple nsp's worth of files stuffed into one nsp. In most cases it will be the base games and its files (cmnt and ncas) and at least the update if not dlc as well

**Comment by Masamune3210** [comment]
NSC_BUILDER can be used to make them, maybe look over there and see if you can glean anything if you have the chance?

**Comment by Masamune3210** [comment]
yeah, as I thought the nsp file is just treated as a archive, you should just be able to scan for all the cmnt files and read them all to figure out what is in a nsp

**Comment by Masamune3210** [comment]
https://github.com/julesontheroad/NSC_BUILDER/issues/135#issuecomment-651758664

here is a link to a issue at NSC_BUILDER's repo explaining the format and how to parse it

**Comment by giwty** [comment]
Thanks, will look into adding this

**Comment by mspykerez** [comment]
Would be nice to add support multicontent XCI to.
I actually have a bunch of games that already come with integrated updates and DLCs that Switch Library Manager says it's missing. Example:

NAMCOT_COLLECTION_NSW-HR > already comes with all Vol.1 DLC;
Sonic_Mania_Plus_NSW-LiGHTFORCE > since it's the plus version it already comes with Encore DLC and also comes with latest update v131072;
Caveman_Warriors_Deluxe_Edition_NSW-LiGHTFORCE > since it's deluxe edition already contains the latest update v131072
Mario_Kart_8_Deluxe_v004_iNTERNAL_NSW-GANT > since it's revision 004 already contains the latest update 1.7.1 v589824;

**Comment by giwty** [comment]
Can you share an example for a multi content NSP?
If you can share a small example (please do it through a pm on gbatemp), then i'll add the support.

**Comment by mspykerez** [comment]
Sorry but as for multi content games I think I only have XCI like the ones I mention above.

**Comment by giwty** [comment]
multi updates on xci/xcz are already supported, will look into adding dlc support as well.

**Comment by Masamune3210** [comment]
Do you want me to just generate one and send it to you over gdrive or something?

**Comment by giwty** [comment]
Exactly, will make it easier for me, as i do not use these.

**Comment by Masamune3210** [comment]
Alright tomorrow after I get off of work I'll make and send you the link to download

**Comment by Masamune3210** [comment]
As far as I know its simply a nsp with more than one cmnt/nca paring inside of it, is it ok if its nsz compressed or does it need to be decompressed?

**Comment by Masamune3210** [comment]
Sent the example to your gbatemp account in a pm, let me know if you need a compressed example or anything else

**Comment by Masamune3210** [comment]
If you can make a build or have a place I can get one, I can test this later today for bugs

**Comment by Masamune3210** [comment]
unfortunately won't be able to test this until next week as I am going to be away from my computer until at least Monday

**Comment by giwty** [comment]
New version is out with this update, enjoy your time off, report back when you can, no rush!

**Comment by Masamune3210** [comment]
Thanks, will report back if I find anything!
