### ISSUE TITLE
ERROR	nsp-update/gui.go:273	unexpected EOF

### ISSUE THREAD

**Issue by roamin31** [giwty/switch-library-manager#51]
[slm.log](https://github.com/giwty/switch-library-manager/files/5322623/slm.log)

ERROR	nsp-update/gui.go:273	unexpected EOF

also 

error: read ecconnreset at tcp.onstreamread (internal/stream_base_commons.js:183:27)

have title and prod files from incognito 1.8.4 in my SLM folder.
log scans 2 files as you can see, there is only those 2 files but once i scan it throws the econnreset error at me and shows nothing in the gui, i reset the program and it needs me to point out the folder where i store the files again, ie deletes the settings i made to point the program to the folder to scan.

great concept but unfortunately its a useless program to me as it doesnt do anything atm, but im excited to see these bugs ironed out and to use this program, if it could scan the switch's memory card to inform of what updates are needed would be an amazing feature too. i thank you for putting the time into this program as it will be very handy to use once the bugs are ironed out.

**Comment by giwty** [comment]
That's actually a problem with Tinfoil providing malformed JSON (https://tinfoil.media/repo/db/titles.json). (https://github.com/blawar/titledb/issues/7)
I will add better error message

**Comment by roamin31** [comment]
how do i go about using this software without any issues atm? the game i have is not showing up in SLM under base or updates.

i also get 2 errors as you see in my OP i also upped my log as well in the OP.

**Comment by giwty** [comment]
Download these 2 files:

1. https://raw.githubusercontent.com/blawar/titledb/master/titles.US.en.json
2. https://raw.githubusercontent.com/blawar/titledb/master/versions.json

Place both files in the same folder as the app exe.
Rename the titles.US.en.json --> titles.json

Restart the app, and it should work

**Comment by roamin31** [comment]
that fixed it, thank you very much.

easy fix, if you know what your doing lol.
cheers for your time to help me out, appreciate it.
