### ISSUE TITLE
Request/Suggestion - blacklist

### ISSUE THREAD

**Issue by pixeltester** [giwty/switch-library-manager#52]
Would it be possible to add a blacklist using titleIDs specifically to prevent certain titles appearing in the missing results?

The use case is to avoid unwanted DLC appearing in the "missing DLCs" results, there are many foreign language pack DLC for example that users may want to exclude.

Thank you

**Comment by johnlescault** [comment]
+1 to this request. Really hoping this project is still alive!

**Comment by giwty** [comment]
Project is still alive, but moving slower now, will add it to next release.

**Comment by giwty** [comment]
Added ability to blacklist/ignore DLC by title ids in v1.4.0
