### ISSUE TITLE
(v.1.3.7) Many missing Key_area_key[key_area_key_application_0a] errors

### ISSUE THREAD

**Issue by johnlescault** [giwty/switch-library-manager#53]
[slm.log](https://github.com/giwty/switch-library-manager/files/5356292/slm.log)

Not sure what you need to troubleshoot this but I will provide what you need if you let me know. (version 1.3.7 with prod.keys installed)

Getting many of the following errors:
- failed to read NSP [reason: missing Key_area_key[key_area_key_application_0a]]
- failed to read split files [reason: missing Key_area_key[key_area_key_application_0a]]

**Comment by giwty** [comment]
That just means you are missing the Switch firmware 10 keys (0a), so any newer title will not work.
You will need to add these to the prod.keys.

**Comment by johnlescault** [comment]
Thanks - you were entirely right. I thought I had updated it but I must of been wrong!
