### ISSUE TITLE
Not working with network drive

### ISSUE THREAD

**Issue by ErikasRaginis** [giwty/switch-library-manager#59]
I have a 10TB samba drive mounted in winsows. When i try scanning, it says
` {3 unable to determine title-Id / version - unable to determine titileId / version }`

**Comment by giwty** [comment]
The error above just means one of the files was not parsed properly, not related to network drive
Do you have keys.prod? that might explain why it cannot parse files.

If you still have issues, please run with debug on (set debug on settings.json), and post the relevant error

**Comment by giwty** [comment]
Closing, please re-open if you have additional info
